# Generated by Django 5.0 on 2025-03-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('number', models.CharField(max_length=25, null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('age', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
