# Generated by Django 5.0 on 2025-03-31 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steganoapp', '0002_registeration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stegoimage', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Steganoapp.registeration')),
            ],
        ),
    ]
