# Generated by Django 5.0 on 2025-04-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Steganoapp', '0003_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decrypt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
